[tools]
gradle = "latest"
java = "latest"

[tasks.build]
run = "gradle build"
sources = ["src/**/*.java"]
outputs = ["build/**/*.class"]

[tasks.start]
run = "gradle run -q"

[tasks.test]
run = "gradle test"
